apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: systemdunit-controller
rules:
- apiGroups:
  - hacks4snacks
  resources:
  - systemdunits
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - list